# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='username',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
