# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='app',
        ),
    ]
