# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170721_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='app',
            new_name='UserModel',
        ),
    ]
