# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloneapp', '0008_auto_20170806_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=555)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloneapp.PostModel')),
            ],
        ),
    ]
